spring:
  application:
    name: demo-ext
  datasource:
    username: test
    password: Test@888!
    url: jdbc:mysql://125.77.165.188:3306/test?useSSL=false&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
#    单机启用host、port：
    host: 125.77.165.188
    port: 6379
#   单机、哨兵公用password、database：
    password: redis@1234!
#    企业管理云的REDIS库：
    database: 10
#   哨兵使用sentinel.master、sentinel.nodes：
#    sentinel:
#      master:
#      nodes:
#   连接池：
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: 5s
        min-idle: 0
        time-between-eviction-runs: 60s
  rabbitmq:
    host: 125.77.165.188
    port: 5672
    username: admin
    password: admin@1234
    virtual-host: qygly
    listener:
      simple:
        # 单个队列的并发消费者的最小数量：
        concurrency: 3
        # 单个队列的并发消费者的最大数量：
        max-concurrency: 10

server:
  port: 11111

qygly:
  ext-jar-debug:
    debugger-name: form-ext